spring:
  application:
    name: queue-project
  datasource:
    url: jdbc:postgresql://localhost:5433/queue_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET:queue-project-app-2026-super-secure-secret-key-minimum-64-character-never-share-this!!!}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 часа в миллисекундах
  header: ${JWT_HEADER:Authorization}
  prefix: ${JWT_PREFIX:Bearer }